### ISSUE TITLE
Extend `core::hash` instead of replacing it

### ISSUE THREAD

**Issue by Liamolucko** [rust-embedded-community/hash32#12]
It's possible to implement `hash32::Hasher` as an extension of `core::hash::Hasher`, rather than a replacement:

```rust
pub trait Hasher: core::hash::Hasher {
    // This isn't the best name, but calling it `finish` would conflict with the method of `core::hash::Hasher`.
    fn finish32(&self) -> u32;
}
```

This would allow using the standard `Hash` type instead of needing a custom version, and also remove the need for a custom derive macro.

Obviously, this would be a breaking change. Even if everything else was kept the same, and a blanket impl of `core::hash::Hasher` for `hash32::Hasher` was used instead of modifying `hash32::Hasher`, that would break any crates which already implemented both.

I've made a draft implementation at https://github.com/Liamolucko/hash32/tree/use-std.

**Comment by japaric** [comment]
I like this idea. Thanks for bringing it up.

> This would allow using the standard Hash type instead of needing a custom version, and also remove the need for a custom derive macro.

This, in particular, is a great plus.

> I've made a draft implementation at https://github.com/Liamolucko/hash32/tree/use-std.

I noticed that `BuildHasherDefault` and `BuildHasher` were also removed. I'd like to keep them. The main dependent of this crate is `heapless` and it relies on `BuildHasherDefault` having a const constructor to allow creating fixed-capacity `IndexMap`s [in const context](https://github.com/japaric/heapless/blob/9fb9cd70451bd8c4e6ccf51ca3c77b8cb033fc27/src/indexmap.rs#L376).

Could you send a PR with `BuildHasherDefault` and `BuildHasher` restored?
